### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by gzzen** [rhysong/dsci-310-group-14#1]
Below is a list of feedback that you can make use of to improve your project. If anything is unclear, please feel free to ask questions under this issue thread. We are looking forward to see your next milestone!

### README.md

- [ ] Please improve one or more incomplete documentation (i.e., group members' names, dependencies) (-1)

### Project organization

- [ ] Please make sufficient use of Github issues for features, fixes, task tracking, and other project-related communications (-2)

- [ ] Please track the progress of the project using [[Github miltstones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones)](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones), and associate this funcationality with issues and pull requests (-2)
- Please make sufficient use of Github project board by associating Github issue cards into the board. The project board should show the current status of the project to the team. (-4)

### Version control workflow

- [ ] Please ensure every feature & fix to be operated under a separate branch, and merge into the main branch using pull requests (-1)
