### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by gzzen** [rhysong/dsci-310-group-14#20]
- [ ] Missing package for `test_getallstars.R` inside container, and incorrect file directory (-2)
```
(base) jovyan@95890f792e69:~/work/Tests$ Rscript ./test_getallstars.R
Error in here("R/01_season_filter.R") : could not find function "here"

Error in test_that("clean_all-stars should return correct data frame",  : 
  could not find function "test_that"
```
After installing required package
```
cannot open file 'data/all_stars_data.csv': No such file or directory
```
- [ ] Similar issue for the other two tests (-3)

- [ ] Test codes have missing documentation (-5)
- [ ] Redundant text in analysis and script files, i.e., codes that are commented out and TODO (you can manage tasks using github issues) (-1)
